#创建docker应用程序模版 使用例如nginx等等

stages:
   - style
   - test
   - deploy
   - release
pep8:
    stage: style
    script:
        - pip install tox
        - tox -e pep8
        
    tags:
      - python2.7
    except:
      - tags    
      

unittest-py27:
    stage: test
    script:
       - pip install tox
       - tox -e py27
    tags:
     - python2.7
     
    except:
     - tags
unittest-py34:
    stage: test
    script:
       - pip install tox
       - tox -e py34
    tags:
     - python3.4
    except:
     - tags
docker-deploy:
   stage: deploy
   script:
    - docker build -t flask-demo .
    - docker push 192.168.33.209:5000/flask-demo
    - if [ $(docker ps -aq --filter name=web) ];  then docker rm -f web;fi 
    - docker run -d --name web -p 5000:5000 flask-demo
   tags:
     - demo
   only:
     - master
docker-image-release:
   stage: release
   script:
    - docker build -t 192.168.33.209:5000/flask-demo:$CI_COMMIT_TAG .
    - docker push 192.168.33.209:5000/flask-demo:$CI_COMMIT_TAG
   tags:
    - demo
   only: 
    - tags
